final Map<int, String> corpus = {
  1: "Flutter is a powerful framework that uses the Dart programming language to build modern mobile applications efficiently",
  2: "Dart language is designed to be fast and optimized for building user interfaces across multiple platforms",
  3: "Flutter framework was developed by Google to allow developers to create cross platform applications with a single codebase",
  4: "Fluter is a common misspelling of Flutter that frequently appears in search engine queries and user inputs",
  5: "Mobile applications can be developed using Flutter and Dart with high performance and smooth user experience",
  6: "Search engines rely heavily on inverted index structures to retrieve documents quickly and accurately",
  7: "Information retrieval systems are responsible for finding relevant documents based on user queries",
  8: "Retrieval models include boolean retrieval models and vector space models for ranking documents",
  9: "Boolean search allows users to combine keywords using operators such as AND OR and NOT",
  10: "Phrase queries require positional index support to ensure words appear in the correct order",
  11: "An inverted index maps each term to a list of document identifiers where the term appears",
  12: "A positional index stores the exact positions of terms inside documents to support phrase searching",
  13: "Text processing steps include tokenization stop word removal and stemming operations",
  14: "Stop words such as is and the are removed during preprocessing to improve retrieval efficiency",
  15: "Stemming reduces different word forms to a common root to improve matching accuracy",
  16: "Phonetic search techniques help systems handle spelling errors made by users",
  17: "The Soundex algorithm groups words that sound similar even if they are spelled differently",
  18: "Flutter and Fluter have similar pronunciation which makes phonetic matching very useful",
  19: "Search systems improve result quality by combining indexing processing and phonetic matching",
  20: "Query processing plays a critical role in retrieving accurate and relevant search results",
};
